### ISSUE TITLE
When placing and breaking stuff.

### ISSUE THREAD

**Issue by k0nker** [MCNSA/MCNSANotes-Bukkit#3]
```
[02:59:41 ERROR]: Could not pass event BlockBreakEvent to MCNSANotes v2.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.jar:git-Paper-52]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.jar:git-Paper-52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.jar:git-Paper-52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.jar:git-Paper-52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:320) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:124) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1236) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_172]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:986) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at uk.co.maboughey.mcnsanotes.listener.PlayerListener.playerBlockBreak(PlayerListener.java:80) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor89.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.jar:git-Paper-52]
        ... 18 more
[02:59:57 ERROR]: Could not pass event BlockPlaceEvent to MCNSANotes v2.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.jar:git-Paper-52]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.jar:git-Paper-52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.jar:git-Paper-52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.jar:git-Paper-52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.jar:git-Paper-52]
        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:154) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.ItemStack.placeItem(ItemStack.java:224) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:541) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1312) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_172]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_172]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:986) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-52]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.NullPointerException
        at uk.co.maboughey.mcnsanotes.listener.PlayerListener.playerBlockPlace(PlayerListener.java:90) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor94.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.jar:git-Paper-52]
        ... 19 more
```

**Comment by maboughey** [comment]
Local Database connection issue.
